---
- hosts: webservers
  become: yes
 
  tasks:
  - name: install apache service
    yum: name=httpd state=installed
  - name: starting apache service
    service: name=httpd state=started

- hosts: dbservers
  become: yes
  
  tasks: 
  - name: install mysql-server
    yum: name=mysql-server state=installed
  - name: starting mysql service
    service: name=mysqld state=started

- hosts: webservers:dbservers
  become: yes
  
  tasks:
  - name: stoping iptables service
    service: name=iptables state=stopped

#- hosts: datacenter
#  become: yes
 
#  tasks:
#  - name: install apache service
#    yum: name=httpd state=removed
#  - name: starting apache service
#    service: name=httpd state=started

#  - name: install mysql-server
#    yum: name=mysql-server state=removed
#  - name: starting mysql service
#    service: name=mysqld state=started

#  - name: stoping iptables service
#    service: name=iptables state=stopped

