---
# handlers file for webserver
- name: restart apache
  service: name=httpd state=restarted
  when: ansible_os_family == 'RedHat'

- name: restart apache2  
  service: name=apache2 state=restarted
  when: ansible_os_family == 'Debian'